// lib/screens/add_patient_screen.dart
import 'package:dental/providers/patient_provider.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:google_fonts/google_fonts.dart';
import '../models/patient.dart';
import '../widgets/main_button.dart'; // Make sure this import is correct

class AddPatientScreen extends StatefulWidget {
  const AddPatientScreen({Key? key}) : super(key: key);

  @override
  State<AddPatientScreen> createState() => _AddPatientScreenState();
}

class _AddPatientScreenState extends State<AddPatientScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameCtrl = TextEditingController();
  final _ageCtrl = TextEditingController();
  final _phoneCtrl = TextEditingController();

  final _dobCtrl = TextEditingController();
  final _emailCtrl = TextEditingController();
  final _addressCtrl = TextEditingController();
  final _emergencyContactNameCtrl = TextEditingController();
  final _emergencyContactPhoneCtrl = TextEditingController();
  final _primaryLanguageCtrl = TextEditingController();
  final _alertsCtrl = TextEditingController();
  final _systemicDiseasesCtrl = TextEditingController();
  final _medicationsCtrl = TextEditingController();
  final _allergiesCtrl = TextEditingController();
  final _pastSurgeriesCtrl = TextEditingController();
  final _lifestyleFactorsCtrl = TextEditingController();
  final _pregnancyLactationStatusCtrl = TextEditingController();
  final _chiefComplaintCtrl = TextEditingController();
  final _pastDentalTreatmentsCtrl = TextEditingController();
  final _previousDentalProblemsCtrl = TextEditingController();
  final _oralHygieneHabitsCtrl = TextEditingController();
  final _lastDentalVisitCtrl = TextEditingController();
  final _lastXRayCtrl = TextEditingController();

  String? _gender;
  bool isLimitReached = false; // State variable for patient limit

  @override
  void initState() {
    super.initState();
    _checkPatientLimit();
  }

  Future<void> _checkPatientLimit() async {
    final patientProvider = Provider.of<PatientProvider>(
      context,
      listen: false,
    );
    await patientProvider
        .loadPatients(); // Ensure the patient list is up-to-date
    if (mounted) {
      setState(() {
        isLimitReached =
            patientProvider.patients.length >=
            PatientProvider.MAX_PATIENT_LIMIT;
      });
    }
  }

  Future<void> _selectDate(TextEditingController controller) async {
    DateTime? initialDate;
    if (controller.text.isNotEmpty) {
      initialDate = DateTime.tryParse(controller.text);
    }
    initialDate ??= DateTime.now();

    DateTime? picked = await showDatePicker(
      context: context,
      initialDate: initialDate,
      firstDate: DateTime(1900),
      lastDate: DateTime(2101),
      builder: (context, child) {
        return Theme(
          data: ThemeData.light().copyWith(
            colorScheme: ColorScheme.light(
              primary: Colors.teal,
              onPrimary: Colors.white,
              onSurface: Colors.black,
            ),
            textButtonTheme: TextButtonThemeData(
              style: TextButton.styleFrom(
                foregroundColor: Colors.teal,
                textStyle: GoogleFonts.montserrat(),
              ),
            ),
            textTheme: TextTheme(
              titleLarge: GoogleFonts.montserrat(),
              bodyLarge: GoogleFonts.montserrat(),
              bodyMedium: GoogleFonts.montserrat(),
            ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null) {
      setState(() {
        controller.text = picked.toIso8601String().substring(0, 10);
      });
    }
  }

  Future<void> _save() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();

      if (_gender == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text(
              'Veuillez sélectionner un sexe.',
            ), // 'Please select a gender.'
            backgroundColor: Colors.red,
          ),
        );
        return;
      }

      final newPatient = Patient(
        // ID will be generated by Supabase or Uuid if not provided
        name: _nameCtrl.text,
        age: int.parse(_ageCtrl.text),
        gender: _gender!,
        phone: _phoneCtrl.text,
        dateOfBirth: _dobCtrl.text.isEmpty ? null : _dobCtrl.text,
        email: _emailCtrl.text.isEmpty ? null : _emailCtrl.text,
        address: _addressCtrl.text.isEmpty ? null : _addressCtrl.text,
        emergencyContactName: _emergencyContactNameCtrl.text.isEmpty
            ? null
            : _emergencyContactNameCtrl.text,
        emergencyContactPhone: _emergencyContactPhoneCtrl.text.isEmpty
            ? null
            : _emergencyContactPhoneCtrl.text,
        primaryLanguage: _primaryLanguageCtrl.text.isEmpty
            ? null
            : _primaryLanguageCtrl.text,
        alerts: _alertsCtrl.text.isEmpty ? null : _alertsCtrl.text,
        systemicDiseases: _systemicDiseasesCtrl.text.isEmpty
            ? null
            : _systemicDiseasesCtrl.text,
        medications: _medicationsCtrl.text.isEmpty
            ? null
            : _medicationsCtrl.text,
        allergies: _allergiesCtrl.text.isEmpty ? null : _allergiesCtrl.text,
        pastSurgeriesHospitalizations: _pastSurgeriesCtrl.text.isEmpty
            ? null
            : _pastSurgeriesCtrl.text,
        lifestyleFactors: _lifestyleFactorsCtrl.text.isEmpty
            ? null
            : _lifestyleFactorsCtrl.text,
        pregnancyLactationStatus: _pregnancyLactationStatusCtrl.text.isEmpty
            ? null
            : _pregnancyLactationStatusCtrl.text,
        chiefComplaint: _chiefComplaintCtrl.text.isEmpty
            ? null
            : _chiefComplaintCtrl.text,
        pastDentalTreatments: _pastDentalTreatmentsCtrl.text.isEmpty
            ? null
            : _pastDentalTreatmentsCtrl.text,
        previousDentalProblems: _previousDentalProblemsCtrl.text.isEmpty
            ? null
            : _previousDentalProblemsCtrl.text,
        oralHygieneHabits: _oralHygieneHabitsCtrl.text.isEmpty
            ? null
            : _oralHygieneHabitsCtrl.text,
        lastDentalVisit: _lastDentalVisitCtrl.text.isEmpty
            ? null
            : _lastDentalVisitCtrl.text,
        lastXRay: _lastXRayCtrl.text.isEmpty ? null : _lastXRayCtrl.text,
      );

      final patientProvider = Provider.of<PatientProvider>(
        context,
        listen: false,
      );

      if (isLimitReached) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              'La limite de ${PatientProvider.MAX_PATIENT_LIMIT} patients a été atteinte. Impossible d\'ajouter plus de patients.',
              style: GoogleFonts.montserrat(),
            ),
            backgroundColor: Colors.red,
            duration: const Duration(seconds: 3),
          ),
        );
        return;
      }

      try {
        bool success = await patientProvider.addPatient(newPatient);
        if (mounted) {
          if (success) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text(
                  'Patient ${newPatient.name} ajouté avec succès !',
                  style: GoogleFonts.montserrat(),
                ),
                backgroundColor: Colors.green,
              ),
            );
            Navigator.of(context).pop(true); // Indicate success
          } else {
            // This 'else' block might be redundant if addPatient always succeeds or throws
            // but kept for safety if addPatient has more complex return logic.
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text(
                  'Échec de l\'ajout du patient. La limite de ${PatientProvider.MAX_PATIENT_LIMIT} patients a peut-être été atteinte.',
                  style: GoogleFonts.montserrat(),
                ),
                backgroundColor: Colors.red,
              ),
            );
          }
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                'Erreur lors de l\'ajout du patient: $e',
                style: GoogleFonts.montserrat(),
              ),
              backgroundColor: Colors.red,
            ),
          );
        }
      }
    }
  }

  Widget _buildSectionHeader(String title) {
    return Padding(
      padding: const EdgeInsets.only(top: 24.0, bottom: 12.0),
      child: Text(
        title,
        style: GoogleFonts.montserrat(
          fontSize: 24,
          fontWeight: FontWeight.bold,
          color: Colors.teal.shade800,
        ),
      ),
    );
  }

  // Modified _buildSection to include card-like styling
  Widget _buildSection({
    required String title,
    required List<Widget> children,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _buildSectionHeader(title),
        Container(
          margin: const EdgeInsets.only(bottom: 20.0), // Space between sections
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(20),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.04),
                blurRadius: 12,
                offset: const Offset(0, 4),
              ),
            ],
          ),
          padding: const EdgeInsets.all(20.0), // Inner padding for the card
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: children,
          ),
        ),
      ],
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String labelText,
    TextInputType keyboardType = TextInputType.text,
    int? maxLines = 1,
    String? Function(String?)? validator,
    VoidCallback? onTap,
    bool readOnly = false,
    Widget? suffixIcon,
    Widget? prefixIcon,
    String? hintText,
    TextInputAction textInputAction = TextInputAction.next,
  }) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 10.0),
      child: TextFormField(
        controller: controller,
        style: GoogleFonts.montserrat(fontSize: 18),
        decoration: InputDecoration(
          labelText: labelText,
          labelStyle: GoogleFonts.montserrat(fontSize: 18),
          hintText: hintText,
          hintStyle: GoogleFonts.montserrat(
            color: Colors.grey.shade500,
            fontSize: 18,
          ),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(15.0),
            borderSide: BorderSide(color: Colors.grey.shade400, width: 1.5),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(15.0),
            borderSide: BorderSide(color: Colors.teal, width: 2.5),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(15.0),
            borderSide: BorderSide(color: Colors.grey.shade400, width: 1.5),
          ),
          filled: true,
          fillColor: Colors.white,
          contentPadding: const EdgeInsets.symmetric(
            vertical: 20.0,
            horizontal: 20.0,
          ),
          suffixIcon: suffixIcon,
          prefixIcon: prefixIcon != null
              ? Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 10.0),
                  child: SizedBox(
                    width: 28.0,
                    height: 28.0,
                    child: Align(
                      alignment: Alignment.center,
                      child: IconTheme(
                        data: IconThemeData(
                          size: 28.0,
                          color: Colors.teal.shade700,
                        ),
                        child: prefixIcon,
                      ),
                    ),
                  ),
                )
              : null,
        ),
        keyboardType: keyboardType,
        maxLines: maxLines,
        validator: validator,
        onTap: onTap,
        readOnly: readOnly,
        textInputAction: textInputAction,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final isTablet = MediaQuery.of(context).size.width >= 600;
    final textScaleFactor = MediaQuery.of(context).textScaleFactor;

    return Scaffold(
      backgroundColor: Colors.grey.shade50,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0, // Remove shadow for a flatter look
        toolbarHeight: 80, // Adjust height as needed
        title: Padding(
          padding: const EdgeInsets.only(
            left: 0.0,
          ), // Adjust padding for title if necessary
          child: Text(
            'Ajouter un nouveau patient', // Add new patient
            style: GoogleFonts.montserrat(
              fontSize:
                  (isTablet ? 32 : 24) * textScaleFactor, // Adjusted font size
              fontWeight: FontWeight.bold,
              color: Colors.teal.shade800,
            ),
          ),
        ),
        leading: Padding(
          padding: const EdgeInsets.only(left: 16.0),
          child: IconButton(
            icon: Icon(
              Icons.arrow_back_ios,
              color: Colors.teal.shade600,
              size: isTablet ? 32 : 28,
            ),
            onPressed: () => Navigator.of(context).pop(),
            tooltip: 'Retour',
          ),
        ),
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          return SingleChildScrollView(
            padding: const EdgeInsets.all(20.0),
            child: ConstrainedBox(
              constraints: BoxConstraints(minHeight: constraints.maxHeight),
              child: IntrinsicHeight(
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      _buildSection(
                        title: 'Informations de base',
                        children: [
                          _buildTextField(
                            controller: _nameCtrl,
                            labelText: 'Nom',
                            validator: (value) {
                              if (value == null || value.isEmpty) {
                                return 'Veuillez entrer un nom';
                              }
                              return null;
                            },
                            prefixIcon: const Icon(Icons.person),
                          ),
                          _buildTextField(
                            controller: _ageCtrl,
                            labelText: 'Âge',
                            keyboardType: TextInputType.number,
                            validator: (value) {
                              if (value == null || value.isEmpty) {
                                return 'Veuillez entrer un âge';
                              }
                              if (int.tryParse(value) == null) {
                                return 'Veuillez entrer un nombre valide';
                              }
                              return null;
                            },
                            prefixIcon: const Icon(Icons.cake),
                          ),
                          Padding(
                            padding: const EdgeInsets.symmetric(vertical: 10.0),
                            child: DropdownButtonFormField<String>(
                              value: _gender,
                              style: GoogleFonts.montserrat(
                                fontSize: 18,
                                color: Colors.black87,
                              ),
                              decoration: InputDecoration(
                                labelText: 'Sexe',
                                labelStyle: GoogleFonts.montserrat(
                                  fontSize: 18,
                                ),
                                prefixIcon: Padding(
                                  padding: const EdgeInsets.symmetric(
                                    horizontal: 10.0,
                                  ),
                                  child: SizedBox(
                                    width: 28.0,
                                    height: 28.0,
                                    child: Align(
                                      alignment: Alignment.center,
                                      child: IconTheme(
                                        data: IconThemeData(
                                          size: 28.0,
                                          color: Colors.teal.shade700,
                                        ),
                                        child: const Icon(Icons.wc_outlined),
                                      ),
                                    ),
                                  ),
                                ),
                                border: OutlineInputBorder(
                                  borderRadius: BorderRadius.circular(15.0),
                                  borderSide: BorderSide(
                                    color: Colors.grey.shade400,
                                    width: 1.5,
                                  ),
                                ),
                                focusedBorder: OutlineInputBorder(
                                  borderRadius: BorderRadius.circular(15.0),
                                  borderSide: BorderSide(
                                    color: Colors.teal,
                                    width: 2.5,
                                  ),
                                ),
                                enabledBorder: OutlineInputBorder(
                                  borderRadius: BorderRadius.circular(15.0),
                                  borderSide: BorderSide(
                                    color: Colors.grey.shade400,
                                    width: 1.5,
                                  ),
                                ),
                                filled: true,
                                fillColor: Colors.white,
                                contentPadding: const EdgeInsets.symmetric(
                                  vertical: 20.0,
                                  horizontal: 20.0,
                                ),
                              ),
                              items: <String>['Male', 'Female'].map((
                                String value,
                              ) {
                                return DropdownMenuItem<String>(
                                  value: value,
                                  child: Text(
                                    value == 'Male' ? 'Homme' : 'Femme',
                                    style: GoogleFonts.montserrat(fontSize: 18),
                                  ),
                                );
                              }).toList(),
                              onChanged: (String? newValue) {
                                setState(() {
                                  _gender = newValue!;
                                });
                              },
                              validator: (val) {
                                if (val == null || val.isEmpty) {
                                  return 'Veuillez sélectionner une option.';
                                }
                                return null;
                              },
                            ),
                          ),
                          _buildTextField(
                            controller: _phoneCtrl,
                            labelText: 'Téléphone',
                            keyboardType: TextInputType.phone,
                            validator: (value) {
                              if (value == null || value.isEmpty) {
                                return 'Veuillez entrer le numéro de téléphone.';
                              }
                              return null;
                            },
                            prefixIcon: const Icon(Icons.phone),
                          ),
                        ],
                      ),
                      _buildSection(
                        title: 'Démographie (Facultatif)',
                        children: [
                          _buildTextField(
                            controller: _dobCtrl,
                            labelText: 'Date de naissance (AAAA-MM-JJ)',
                            readOnly: true,
                            onTap: () => _selectDate(_dobCtrl),
                            prefixIcon: const Icon(Icons.calendar_today),
                          ),
                          _buildTextField(
                            controller: _emailCtrl,
                            labelText: 'Email',
                            keyboardType: TextInputType.emailAddress,
                            prefixIcon: const Icon(Icons.email),
                          ),
                          _buildTextField(
                            controller: _addressCtrl,
                            labelText: 'Adresse',
                            maxLines: null,
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(Icons.location_on),
                          ),
                          _buildTextField(
                            controller: _emergencyContactNameCtrl,
                            labelText: 'Nom du contact d\'urgence',
                            prefixIcon: const Icon(Icons.contact_emergency),
                          ),
                          _buildTextField(
                            controller: _emergencyContactPhoneCtrl,
                            labelText: 'Téléphone du contact d\'urgence',
                            keyboardType: TextInputType.phone,
                            prefixIcon: const Icon(Icons.phone_in_talk),
                          ),
                          _buildTextField(
                            controller: _primaryLanguageCtrl,
                            labelText: 'Langue principale',
                            prefixIcon: const Icon(Icons.language),
                          ),
                        ],
                      ),
                      _buildSection(
                        title: 'Antécédents médicaux (Facultatif)',
                        children: [
                          _buildTextField(
                            controller: _alertsCtrl,
                            labelText: 'Alertes',
                            hintText: 'Ex: Diabète, problèmes cardiaques',
                            maxLines: null, // Allow multiple lines
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(Icons.warning),
                          ),
                          _buildTextField(
                            controller: _systemicDiseasesCtrl,
                            labelText: 'Maladies systémiques',
                            hintText: 'Ex: Hypertension, asthme',
                            maxLines: null, // Allow multiple lines
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(
                              Icons.medical_services_outlined,
                            ),
                          ),
                          _buildTextField(
                            controller: _medicationsCtrl,
                            labelText: 'Médicaments',
                            hintText: 'Ex: Insuline, anti-inflammatoires',
                            maxLines: null, // Allow multiple lines
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(Icons.medication),
                          ),
                          _buildTextField(
                            controller: _allergiesCtrl,
                            labelText: 'Allergies',
                            hintText: 'Ex: Pénicilline, latex',
                            maxLines: null, // Allow multiple lines
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(Icons.do_not_disturb),
                          ),
                          _buildTextField(
                            controller: _pastSurgeriesCtrl,
                            labelText:
                                'Chirurgies antérieures / Hospitalisations',
                            hintText: 'Ex: Appendicectomie, fracture',
                            maxLines: null, // Allow multiple lines
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(Icons.cut),
                          ),
                          _buildTextField(
                            controller: _lifestyleFactorsCtrl,
                            labelText:
                                'Facteurs de mode de vie (Tabac, Alcool, etc.)',
                            hintText: 'Ex: Fumeur, consommation modérée',
                            maxLines: null, // Allow multiple lines
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(Icons.sports_baseball),
                          ),
                          _buildTextField(
                            controller: _pregnancyLactationStatusCtrl,
                            labelText: 'Statut de grossesse/allaitement',
                            hintText: 'Ex: Enceinte (3e trimestre), allaite',
                            maxLines: null, // Allow multiple lines
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(Icons.pregnant_woman),
                          ),
                        ],
                      ),
                      _buildSection(
                        title: 'Antécédents dentaires (Facultatif)',
                        children: [
                          _buildTextField(
                            controller: _chiefComplaintCtrl,
                            labelText: 'Plainte principale',
                            hintText: 'Ex: Mal de dents, carie',
                            maxLines: null, // Allow multiple lines
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(Icons.sick),
                          ),
                          _buildTextField(
                            controller: _pastDentalTreatmentsCtrl,
                            labelText: 'Traitements dentaires antérieurs',
                            hintText: 'Ex: Plombages, extractions',
                            maxLines: null, // Allow multiple lines
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(Icons.healing_outlined),
                          ),
                          _buildTextField(
                            controller: _previousDentalProblemsCtrl,
                            labelText: 'Problèmes dentaires antérieurs',
                            hintText: 'Ex: Gencives sensibles, abcès',
                            maxLines: null, // Allow multiple lines
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(Icons.sick_outlined),
                          ),
                          _buildTextField(
                            controller: _oralHygieneHabitsCtrl,
                            labelText: 'Habitudes d\'hygiène buccale',
                            hintText: 'Ex: Brossage 2x/jour, fil dentaire',
                            maxLines: null, // Allow multiple lines
                            keyboardType: TextInputType.multiline,
                            textInputAction: TextInputAction.newline,
                            prefixIcon: const Icon(Icons.brush),
                          ),
                          _buildTextField(
                            controller: _lastDentalVisitCtrl,
                            labelText: 'Dernière visite dentaire (AAAA-MM-JJ)',
                            readOnly: true,
                            onTap: () => _selectDate(_lastDentalVisitCtrl),
                            prefixIcon: const Icon(Icons.event_available),
                          ),
                          _buildTextField(
                            controller: _lastXRayCtrl,
                            labelText: 'Dernière radiographie (AAAA-MM-JJ)',
                            readOnly: true,
                            onTap: () => _selectDate(_lastXRayCtrl),
                            prefixIcon: const Icon(Icons.medical_services),
                          ),
                        ],
                      ),
                      const SizedBox(height: 120),
                    ],
                  ),
                ),
              ),
            ),
          );
        },
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.endFloat,
      floatingActionButton: MainButton(
        onPressed: isLimitReached ? null : _save, // This now works correctly
        label: 'Enregistrer le patient',
        icon: Icons.save,
        backgroundColor: isLimitReached ? Colors.grey : Colors.teal,
        foregroundColor: Colors.white,
        heroTag: 'addPatientSaveButton', // Added unique heroTag
      ),
    );
  }
}
